close a merge request only once

diff --git a/bin/close-mr b/bin/close-mr
--- a/bin/close-mr
+++ b/bin/close-mr
@@ -19,15 +19,19 @@ BODY="{
 	\"state_event\": \"close\"
 }";
 
-for mr in "$@"; do
-	RETURN="$(curl -X PUT "$ENDPOINT"/merge_requests/"$mr" \
-		--header "PRIVATE-TOKEN: $(secret-tool lookup org.gitlab.leo.mkmr token)" \
-		--header "Content-Type: application/json" \
-		--data "$BODY" --silent --output /dev/null --write-out "%{http_code}")"
+if [ -z "$1" ]; then
+	exit 1
+fi
 
-	if [ "$RETURN" -eq 200 ]; then
-		echo "Closed #$mr"
-	else
-		echo "Failed to close #$mr"
-	fi
-done
+mr="$1"
+
+RETURN="$(curl -X PUT "$ENDPOINT"/merge_requests/"$mr" \
+	--header "PRIVATE-TOKEN: $(secret-tool lookup org.gitlab.leo.mkmr token)" \
+	--header "Content-Type: application/json" \
+	--data "$BODY" --silent --output /dev/null --write-out "%{http_code}")"
+
+if [ "$RETURN" -eq 200 ]; then
+	echo "Closed #$mr"
+else
+	echo "Failed to close #$mr"
+fi
