update this thing

diff --git a/bin/dabuild b/bin/dabuild
--- a/bin/dabuild
+++ b/bin/dabuild
@@ -5,22 +5,45 @@
 
 set -e
 
+die () {
+  printf >&2 "%s\n" "$@"
+  exit 1
+}
+
 ## debug
-if [ "$DOCKER_ABUILD_DEBUG" = "true" ]; then
+if [ "$DABUILD_DEBUG" = "true" ]; then
   set -x
   PS4='$LINENO: '
 fi
 
 ## check running from within an `aports` tree
-if [ "${PWD%*/aports*}" = "$PWD" ]; then
-  echo "Error: expecting to be run from within an aports tree!"
-  echo "Could not find '/aports' in the current path ($PWD)"
+if [ "${PWD%*/aports/*}" = "$PWD" ]; then
+  die "Error: expecting to be run from within an aports tree!" \
+      "Could not find '/aports/' in the current path: $PWD"
   exit 1
 fi
 
+## allow setting of arch by env variable
+[ ! "$DABUILD_ARCH" ] && DABUILD_ARCH=$(uname -m)
+case "$DABUILD_ARCH" in
+  x86|x86_64|aarch64|armhf|armv7 ) ;;
+  * ) die "Unsupported arch \"$DABUILD_ARCH\" detected." \
+          "Expected one of: x86|x86_64|aarch64|armhf|armv7" \
+          "You may force it setting DABUILD_ARCH=\"xxx\" in invocation";;
+esac
+
+## allow setting of `docker` command by env variable
+[ ! "$DABUILD_DOCKER" ] && DABUILD_DOCKER=docker
+case "$DABUILD_DOCKER" in
+  podman|docker ) ;;
+  * ) die "Unsupported docker CLI replacement \"$DABUILD_DOCKER\" detected." \
+          "Expected one of: docker|podman"
+      ;;
+esac
+
 ## use branch to figure out most appropriate alpine version
-if [ "$DOCKER_ABUILD_VERSION" ]; then
-  ABUILD_VERSION=$DOCKER_ABUILD_VERSION
+if [ "$DABUILD_VERSION" ]; then
+  ABUILD_VERSION=$DABUILD_VERSION
 else
   APORTS_BRANCH=$(git status | head -1)
   APORTS_BRANCH="${APORTS_BRANCH##*[ /]}"
@@ -30,39 +53,65 @@ else
       ;;
 
     * )
-      ABUILD_VERSION=edge-x86_64
+      ABUILD_VERSION=edge
       ;;
   esac
 fi
 
+## check $DABUILD_PACKAGES is a writable directory
+ABUILD_PACKAGES=${DABUILD_PACKAGES:-${PWD%/aports/*}/packages/${ABUILD_VERSION}}
+
+mkdir -p $ABUILD_PACKAGES
+if [ ! \( -d "$ABUILD_PACKAGES" -a -w "$ABUILD_PACKAGES" \) ]; then
+  die "Error: invalid or unwritable packages directory specified!" \
+      "ABUILD_PACKAGES = '$ABUILD_PACKAGES'" \
+      "DABUILD_PACKAGES = '$DABUILD_PACKAGES'"
+fi
+
 ## setup volumes; use named volumes as cache if desired
-ABUILD_VOLUMES="
-    -v ${HOME}/.abuild:/home/builder/.abuild
-    -v ${HOME}/.abuild:${HOME}/.abuild
-    -v ${PWD%/aports*}/aports:/home/builder/aports
-	-v ${HOME}/packages:${HOME}/packages
-	-v ${HOME}/packages:/home/builder/packages
-	-v /etc/apk/repositories:/etc/apk/repositories
-	-v /etc/apk/keys:/etc/apk/keys
-	-v /var/cache/distfiles:/var/cache/distfiles
-	-v /var/cache/apk:/var/cache/apk
-	-v /etc/abuild.conf:/etc/abuild.conf
-	-v /usr/bin/abuild:/usr/bin/abuild
-"
-if [ "$DOCKER_ABUILD_CACHE" = "true" ]; then
-  for v in bin etc lib sbin usr var home/builder/packages ; do
-    vol=abuild-$ABUILD_VERSION-${v//\//_}
-    if [ "$DOCKER_ABUILD_CLEAN" = "true" ]; then
+ABUILD_VOLUMES="-v ${HOME}/.abuild:/home/builder/.abuild \
+  -v ${HOME}/.ccache:/home/builder/.ccache \
+  -v ${PWD%/aports/*}/aports:/home/builder/aports \
+  -v /etc/apk/repositories:/etc/apk/repositories
+  -v /var/cache/distfiles:/var/cache/distfiles
+  -v /var/cache/apk:/var/cache/apk
+  -v ${HOME}/packages:${HOME}/packages
+  -v ${ABUILD_PACKAGES}:/home/builder/packages"
+
+if [ -f "/etc/abuild.conf" ]; then
+  ABUILD_VOLUMES="$ABUILD_VOLUMES -v /etc/abuild.conf:/etc/abuild.conf:ro"
+fi
+
+if [ -w "/var/cache/distfiles" ]; then
+  ABUILD_VOLUMES="$ABUILD_VOLUMES -v /var/cache/distfiles:/var/cache/distfiles"
+fi
+
+if [ "$DABUILD_CACHE" = "true" ]; then
+  for v in bin etc lib sbin usr var ; do
+    vol=abuild-$ABUILD_VERSION-$DABUILD_ARCH-${v//\//_}
+    if [ "$DABUILD_CLEAN" = "true" ]; then
       ## clean the cache if requested
-      docker rm -f $(docker ps -qaf "volume=$vol") >/dev/null 2>/dev/null || true
+      docker rm -f $(docker ps -qaf "volume=$vol") >/dev/null 2>&1 || true
       docker volume rm $vol >/dev/null
+    fi
+
+    if docker volume ls -f 'name=$v' | grep $v >/dev/null ; then
       docker volume create $vol >/dev/null
     fi
     ABUILD_VOLUMES="$ABUILD_VOLUMES -v $vol:/$v"
   done
 fi
 
+ABUILD_RM="--rm"
+if [ "$DABUILD_RM" = "false" ]; then
+  ABUILD_RM=""
+fi
+
 ## go!
-ABUILD_WORKDIR=/home/builder/aports${PWD#*/aports}
-DOCKER="docker run --rm -ti $ABUILD_VOLUMES -e DOCKER_ABUILD_DEBUG $DOCKER_ABUILD_ARGS"
-$DOCKER --workdir $ABUILD_WORKDIR alpinelinux/docker-abuild:$ABUILD_VERSION "$@"
+docker run --tty --interactive \
+       $ABUILD_RM \
+       $ABUILD_VOLUMES \
+       -e DABUILD_DEBUG \
+       $DABUILD_ARGS \
+       --workdir /home/builder/aports/${PWD#*/aports/} \
+       alpinelinux/docker-abuild:$ABUILD_VERSION-$DABUILD_ARCH "$@"
