allow TARGET_BRANCH to push to another branches

diff --git a/bin/mgmr b/bin/mgmr
--- a/bin/mgmr
+++ b/bin/mgmr
@@ -22,7 +22,7 @@ if [ "$#" -gt 1 ]; then
 	# shellcheck disable=2064
 	trap "rm -rf '$tmpdir'" INT EXIT
 
-	branch="$1-$(</dev/urandom tr -dc A-Za-z0-9-_ | dd bs=22 count=1 2>/dev/null)"
+	branch="${TARGET_BRANCH:-merge}-$(</dev/urandom tr -dc A-Za-z0-9-_ | dd bs=22 count=1 2>/dev/null)"
 	git switch --force-create "$branch" master
 
 	for mr in "$@"; do
@@ -51,20 +51,20 @@ if [ "$#" -gt 1 ]; then
 		# that were merged
 		comment-mr "$mr" 'This was merged as the following commits:
 
-'"$(cat "$tmpdir"/"$mr")"'
+'$(cat "$tmpdir"/"$mr")'
 
 Thanks for your contribution' &
 	done
 	wait
 
 else
-	checkmr "$1" || die "Failed to check out mr !$1"
+	checkmr "$1" "${TARGET_BRANCH:-mgmr}" || die "Failed to check out mr !$1"
 	commits="$(gcp | cut -d ' ' -f 1)"
 	mgbr || die "Failed to merge mr !$1"
 	close-mr "$1" &
 	comment-mr "$1" 'This was merged as the following commits:
 
-'"$commits"'
+'$commits'
 
 Thanks for your contribution' &
 	wait
