bin/mgpr: delete branches in parallel after the fect.

diff --git a/bin/mgpr b/bin/mgpr
--- a/bin/mgpr
+++ b/bin/mgpr
@@ -6,7 +6,14 @@ user="$(get-repo-config username)"
 repo_name="$(get-repo-config repo-name)"
 repo_owner="$(get-repo-config repo-owner)"
 
+# Retry counter
 r=0
+
+# PR numbers that failed
+failed=""
+
+# Branches to be deleted
+branches=""
 
 cd "$(xdistdir)" || exit
 
@@ -22,12 +29,11 @@ do
 	label="$(echo "$prinfo" | awk '/.head.label/ { print $2 }')"
 	title="$(echo "$prinfo" | awk -P '/.title/ { for(i=2;i<=NF;i++) print $i}' | paste -sd ' ')"
 
-	response="$(hub api repos/"${repo_owner}"/"${repo_name}"/pulls/"$1"/merge \
-		 -X PUT -F merge_method=rebase --flat)" ||
+	hub api repos/"${repo_owner}"/"${repo_name}"/pulls/"$1"/merge \
+		 -X PUT -F merge_method=rebase --flat >/dev/null 2>&1 ||
 		 {
-			 printerr "Failed to merge $1" ;
 			 r=$((r+1))
-			 [ $r -gt 1 ] && { echo "$response" | grep -o '^.message.*' ; exit $r ; }
+			 [ $r -gt 1 ] && { failed="${failed} $1" ; shift ; }
 			 continue ;
 		 } &&
 		 {
@@ -37,14 +43,17 @@ do
 	
 	shift
 
-
 	if [ "$(echo "$label" | cut -d : -f1)" = "$user" ]; then
-		dlbr $(echo "$label" | cut -d : -f2)
+		branches="${branches} $(echo "$label" | cut -d : -f2)"
 	fi
+done
 
-	branch="$(echo "$label" | cut -d : -f2)"
-	if git rev-parse --verify "$repo" >/dev/null 2>&1
-	then
-		dlbr $branch
-	fi
+for f in $branches; do
+	dlbr $f &
+done
+
+wait
+
+for f in $failed; do
+	printerr "Failed to merge #$f"
 done
